### PR TITLE
Add headers so that it compiles with libboost1.74-dev

### PR DESCRIPTION
**Pull request by hannahbast**
Add missing boost header to `TagList.h` and `Way.h`, thus fixing the omission of these includes in libboost1.74 (will be fixed again in 1.75 or 1.76, but we don't have that yet on Ubuntu 20.04).

### CODE REVIEW

**Review by patrickbr — APPROVED** [review]
Works on my machine, thanks Hannah!

**Comment by lehmann-4178656ch** [comment]
This breaks building with ` libboost1.71` which is supplied by `Ubuntu 20.04.4` and thus the building of the docker containers.

```
[ 16%] Building CXX object src/CMakeFiles/osm2rdf_library.dir/osm/Area.cpp.o
/app/src/../include/osm2rdf/osm/TagList.h:25:10: error: 'boost/serialization/library_version_type.hpp' file not found [clang-diagnostic-error]
#include "boost/serialization/library_version_type.hpp"
         ^
```

```
root@871ebbd64c8c:/# dpkg -l | grep boost
ii  libboost-dev:amd64                   1.71.0.0ubuntu2                   amd64        Boost C++ Libraries development files (default version)
ii  libboost-serialization-dev:amd64     1.71.0.0ubuntu2                   amd64        serialization library for C++ (default version)
ii  libboost-serialization1.71-dev:amd64 1.71.0-6ubuntu6                   amd64        serialization library for C++
ii  libboost-serialization1.71.0:amd64   1.71.0-6ubuntu6                   amd64        serialization library for C++
ii  libboost1.71-dev:amd64               1.71.0-6ubuntu6                   amd64        Boost C++ Libraries development files
```

```
root@871ebbd64c8c:/# cat /etc/apt/sources.list | grep -v '#'
deb http://archive.ubuntu.com/ubuntu/ focal main restricted
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ focal universe
deb http://archive.ubuntu.com/ubuntu/ focal-updates universe
deb http://archive.ubuntu.com/ubuntu/ focal multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
deb http://security.ubuntu.com/ubuntu/ focal-security universe
deb http://security.ubuntu.com/ubuntu/ focal-security multiverse
```
How did you install a newer boost on Ubuntu 20.04?

**Review by lehmann-4178656ch — CHANGES_REQUESTED** [review]
As mentioned in the other commit, this breaks the containers.

**Comment by patrickbr** [comment]
Forgot to include "boost/version.hpp", sorry.

**Review by lehmann-4178656ch — APPROVED** [review]
Thank you for the changes, Patrick. The container can be build again.
